name: Test-action-checkout
on: [push]

jobs:
  using-checkout-actions:
    runs-on: ubuntu-latest
    steps:
      - name: list file before
        run: |
          pwd
          ls -la
      - name: use actions checkout
        uses: actions/checkout@v4
      - name: list file after
        run: |
          pwd
          ls -la
            