name: Checkout-dir
on: push

jobs:
  checkout-and-display-file:
    runs-on: ubuntu-latest
    steps:
      - name: list files before
        run: |
          pwd
          ls -l
          echo 'hello wodl'
      - name: checkout
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout main
      - name: list file after
        run: ls -a
    