name: First Workflow
on: 
  push:
    paths: .github/workflows/first-actions.yml
jobs:
  run-shell-commands: 
    runs-on: ubuntu-latest
    steps:
      - name: echo string
        run: echo 'Hello World'
      - name: Multiline command
        run: |
          python --version
          node -v
  parallel-job-macos:
    runs-on: macos-latest
    steps:
        - name: view sw version
          run: sw_vers
  dependent-job:
    runs-on: windows-latest
    needs: [run-shell-commands] 
    steps:
      - name: echo a string
        run: Write-Output "Windows string"
      - name: Error step
        run: doesnotexitss don't run