name: Working dir and shell
on : push
defaults:
    run:
        shell: bash
        working-directory: /home/lgb
jobs:
    display-wd-info:
        runs-on: ubuntu-latest
        steps:
            - name: Display
              run: |
                pwd
                ls -a
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE

    display-wd-info-windows:
        runs-on: windows-latest
        steps:
            - name: Display
              run: |
                pwd
                ls -a
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE