name: Working dir and shell
on :
    push:
        paths:
            - .github/workflows/working-dir.yml
defaults:
    run:
        shell: bash
jobs:
    display-wd-info:
        runs-on: ubuntu-latest
        steps:
            - name: Display
              run: |
                pwd
                ls -a
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE
            - name: dir
              working-directory: /home/runner
              run: pwd

    display-wd-info-windows:
        runs-on: windows-latest
        steps:
            - name: Display
              run: |
                pwd
                ls -a
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE